### ISSUE TITLE
Move swift code into subspec

### ISSUE THREAD

**Issue by hfossli** [contentful-labs/Concorde#15]
Hi! We love your library! Very nice. The most interesting part in this project for me is the `CCBufferedImageDecoder` in pair with the library. In my eyes the `CCBufferedImageView.swift` is more like an example of how to integrate. Therefore I created this https://github.com/agens-no/CCBufferedImageDecoder

Ideally for me we would just change the podspec in this repo to either a) move the swift stuff into a subspec or b) remove the swift stuff or c) use one of the [ports].(https://github.com/ljfantin/Concorde/blob/feature/support_ios_7/Code/CCBufferedImageView.m).

Anyways, just though I should let you know.

**Comment by neonichu** [comment]
I think it would be fine to move the image view into its own subspec, called "UI" or something like that. If you were considering to submit a PR with that change, I'd be happy to accept it!

**Comment by neonichu** [comment]
Solved by #16

**Comment by hfossli** [comment]
Awesome. I'll delete that repo once the new podspec is public. :)

**Comment by hfossli** [comment]
I would highly appreciate if you could publish the new podspec 👍

**Comment by neonichu** [comment]
Sorry, still dealing with getting the test suite to actually work again with Xcode 7.3.1

**Comment by neonichu** [comment]
Allright, has been shipped now as 0.2.0
