### ISSUE TITLE
Add support for iOS7

### ISSUE THREAD

**Issue by mheras** [contentful-labs/Concorde#5]
Is it possible to add support for iOS7? When doing `pod install`, I see this lib only works on 8+. Thank you.

**Comment by neonichu** [comment]
Unfortunately, that won't be possible, because it is partially written in Swift, which can only be integrated in a dynamic framework and those are only available on iOS 8 or newer.

**Comment by mheras** [comment]
@neonichu Would it be difficult to port the swift code to objc?

**Comment by mheras** [comment]
@neonichu I mean, maybe if you see no issues at all, I can try porting the code to objc and doing a pull request.

**Comment by neonichu** [comment]
Should be possible, could live on a branch if you contribute it
